#!/bin/sh

sxhkd &

bspc monitor -d Home Web Shell Games Media

bspc monitor DP1 -n 0 -d Home Web Shell Games Media
bspc monitor VGA1 -n 0 -d AWS

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1'
bspc rule -a Konsole desktop='^3'

## color settings
bspc config focused_border_color "#d8dee8"
bspc config normal_border_color "#2f343f"
$HOME/.config/polybar/launch.sh
